### ISSUE TITLE
Missing Elements for Gift: Shroud of the Afterlife

### ISSUE THREAD

**Issue by jasonmc1993** [TheErikkuBlade/pf2e-relics#1]
Howdy!

Coincidentally, I had begun working on my own Compendia Module to handle at least some of these effects for a Campaign I participate in - and at the time - there wasn't an existing Compendium to cover Relics & their Gifts - as it would appear, your initial commit happened just a day after mine did here: https://github.com/jasonmc1993/pf2e-relics - but you'd probably been working on this for awhile - whereas I had just started with the effects pertinent to my campaign.

After noticing this with my GM - I went through a quick review of the effects I had worked on, and noted that Gift: Shroud of the Afterlife from the Death Domain is missing a couple of effects as covered here: https://2e.aonprd.com/Relics.aspx?ID=21

Namely, you appear to be missing the Poison Resistance and the +1 Status Bonus to Saves with the  death effects, diseases effects that would make you paralyzed, poisoned and sleep.

Poison Resistance: `{"key":"Resistance","type":"poison","value":"max(1,floor(@actor.level/2))"}`
Flat Modifier to Saves: 
```
{
  "key": "FlatModifier",
  "label": "Shroud of the Afterlife",
  "selector": "saving-throw",
  "value": 1,
  "type": "status",
  "predicate": [
    {
      "or": [
        "death",
        "disease",
        "effect:poison",
        "effect:paralyzed",
        "effect:sleep"
      ]
    }
  ]
}
```

Thanks for your hard work - and for beating me to the punch!

**Comment by TheErikkuBlade** [comment]
Thanks for catching this! I'll push this for the next update (which will be soon once I get a look at what all has changed in the remaster handling of Relics)

**Comment by jasonmc1993** [comment]
> Thanks for catching this! I'll push this for the next update (which will be soon once I get a look at what all has changed in the remaster handling of Relics)

I'd be happy to assist if I can - if you'd like the assistance.

**Comment by TheErikkuBlade** [comment]
I've already got the fix implemented, just doing some other edits with the module, the update will be pushed later tonight
