### ISSUE TITLE
Propelling Winds Error

### ISSUE THREAD

**Issue by Hackor** [TheErikkuBlade/pf2e-relics#3]
It seems that the Air Gift, Propelling Winds, has the incorrect rule elements. The rule elements used give you the effects of the Divine Retribution gift.
![image](https://github.com/user-attachments/assets/278f055c-ed71-4816-b501-a0d0515fadf5)

**Comment by TheErikkuBlade** [comment]
Ah, I must have missed that, thanks for calling this out - I'll push an update soon!
