### ISSUE TITLE
Heaven's Grace minor fix

### ISSUE THREAD

**Issue by MothMariner** [TheErikkuBlade/pf2e-relics#4]
Had Heaven's Grace on my relic, saw that it had a toggle and realised it could work without one, like below:

`{
  "key": "FlatModifier",
  "selector": "ac",
  "value": 1,
  "type": "status",
  "predicate": [
    "origin:trait:fiend"
  ]
}`

**Comment by TheErikkuBlade** [comment]
Thanks for your contribution! I'll get this pushed for the next update, but right now I am visiting family for the holidays, so once I'm back home I'll get to work on it
